[BE-05] Add comments
knowde-academy/cookbook-BBE2 pull request #2
Opened 2022-07-14 06:31 UTC by Enriquee98

https://trello.com/c/SfakkMcW

2022-07-14 08:40 UTC, grabomarcin commented on app/controllers/api/v1/recipes_controller.rb
> +        @recipe.cooking_time ||= 'unknow'
👀

2022-07-14 08:40 UTC, plokijro commented on app/controllers/api/v1/recipes_controller.rb
> +        @recipe.cooking_time ||= 'unknow'
What's going on here? 😁

2022-07-14 08:40 UTC, grabomarcin commented on app/serializers/comment_serializer.rb
> + ANON = 'annonymous'
Use come better name for that const and move that above `attributes` :p

2022-07-14 08:41 UTC, grabomarcin commented on app/serializers/recipe_serializer_show.rb
> +end
You can inherit that serializer from `RecipeSerializer` and just add what is missing.

2022-07-14 08:42 UTC, grabomarcin commented on skrypt.sh
> +rails s -b $IP_ADDR -p 8082
```suggestion
rails s -b $IP_ADDR -p 8082

```

2022-07-14 08:42 UTC, plokijro commented on app/serializers/recipe_serializer.rb
> +  end
Comments should be returned only in show recipe endpoint

2022-07-14 08:44 UTC, plokijro commented on spec/controllers/api/v1/comment_serializer_spec.rb
> +end
Run rubocop please

2022-07-14 08:44 UTC, grabomarcin commented on spec/controllers/api/v1/comment_serializer_spec.rb
> +end
```suggestion
require 'rails_helper'

RSpec.describe CommentSerializer do
  subject { described_class.new(comment).to_h }
  
  let(:comment) { build :comment }
  
  it { is_expected.to include(body: comment.body) }
  it { is_expected.to include(id: comment.id) }
  it { is_expected.to include(created_at: comment.created_at) }
  
  describe '#author' do
    context 'when comment with author is present' do
      it { is_expected.to include(author: comment.author) }
    end
    
    context 'when comment with author is nil' do
      let(:comment) { build :comment, author: nil }
      it { is_expected.to include(author: described_class::CONST_WHICH_YOU_DEFINED) }
    end
  end
end

```

You can call const here. Please use rubocop to fix syntax

2022-07-14 08:44 UTC, grabomarcin commented on spec/factories/comments.rb
> +end
```suggestion
end

```

2022-07-14 08:45 UTC, grabomarcin commented on spec/models/comment_spec.rb
> +  describe 'association' do
```suggestion
  describe 'associations' do
```

2022-07-15 09:39 UTC, plokijro commented on app/models/recipe.rb
>  end
`cooking_time`? Isn't it from another task?

2022-07-15 09:40 UTC, plokijro commented on app/serializers/comment_serializer.rb
> +  end
```suggestion
  attributes :id, :author, :body, :created_at
  
  def author
    return ANONYMOUS unless object.author

    object.author
  end
```

2022-07-15 09:41 UTC, plokijro commented on app/serializers/recipe_show_serializer.rb
> +  has_many :comments
```suggestion
  attributes :cooking_time
  
  has_many :comments
```

2022-07-15 09:43 UTC, plokijro commented on spec/factories/comments.rb
> +    recipe
```suggestion
    recipe
    author { Faker::Name.name }
    body { Faker::ChuckNorris.fact }
```
Associations should be before attributes

2022-07-15 09:54 UTC, grabomarcin requested changes

2022-07-15 09:54 UTC, grabomarcin commented on app/controllers/api/v1/comments_controller.rb
> +          render json: { errors: comment.errors.to_s }, status: :unprocessable_entity
```suggestion
          render json: { errors: comment.errors.full_messages }, status: :unprocessable_entity
```
IMO it's better

2022-07-15 09:54 UTC, grabomarcin commented on app/controllers/api/v1/recipes_controller.rb
> +
```suggestion
```

2022-07-15 09:54 UTC, grabomarcin commented on app/models/recipe.rb
>    validates :name, presence: true
```suggestion

  validates :name, presence: true
```

2022-07-15 09:54 UTC, grabomarcin commented on app/models/recipe.rb
> +
```suggestion
  validates :cooking_time, numericality: { greater_than: 0 }
  validates :video_link, allow_blank: true, url: true
```

2022-07-15 09:54 UTC, grabomarcin commented on app/serializers/comment_serializer.rb
> +  end
```suggestion
  ANONYMOUS = 'annonymous'.freeze
  
  attributes :id, :author, :body, :created_at
  
  def author
    return ANONYMOUS unless object.author

    object.author
  end
```

2022-07-15 09:54 UTC, grabomarcin commented on app/serializers/recipe_show_serializer.rb
>    end
👀

2022-07-15 09:54 UTC, grabomarcin commented on db/migrate/20220713071428_create_comments.rb
> +
```suggestion
```

2022-07-15 09:54 UTC, grabomarcin commented on spec/factories/comments.rb
> +    recipe
```suggestion
    recipe
    author { Faker::Name.name }
    body { Faker::ChuckNorris.fact }
```

2022-07-15 11:12 UTC, grabomarcin commented on app/models/comment.rb
> +  validates :author, allow_blank: true, length: { minimum: 3 }
```suggestion
  belongs_to :recipe

  validates :body, presence: true, length: { minimum: 10 }
  validates :author, allow_blank: true, length: { minimum: 3 }
```

2022-07-18 10:14 UTC, plokijro commented on spec/serializers/comment_serializer_spec.rb
> +    end
```suggestion
    context 'with author' do
      it { is_expected.to include(author: comment.author) }
    end

    context 'without author' do
      let!(:comment) { create :comment, author: nil }

      it { is_expected.to include(author: described_class::ANONYMOUS) }
    end
```

2022-07-18 11:24 UTC, grabomarcin commented on app/models/recipe.rb
> +  INCLUSION_ERROR_MESSAGE = 'must be integer in range 1-5 inclusive'.freeze
Move const definitions up

2022-07-18 11:24 UTC, grabomarcin commented on app/models/recipe.rb
> +    validates :level, allow_nil: true,
Fix syntax

2022-07-18 11:26 UTC, grabomarcin commented on app/serializers/recipe_show_serializer.rb
> +
unnecessary empty line

2022-07-18 11:37 UTC, grabomarcin commented on app/models/recipe.rb
>    INCLUSION_ERROR_MESSAGE = 'must be integer in range 1-5 inclusive'.freeze
```suggestion
  INCLUSION_ERROR_MESSAGE = 'must be integer in range 1-5 inclusive'.freeze
  
```

2022-07-18 11:38 UTC, grabomarcin commented on app/serializers/recipe_show_serializer.rb
> +
```suggestion

```

2022-07-18 11:44 UTC, grabomarcin commented on app/serializers/recipe_show_serializer.rb
> +  has_many :comments
```suggestion
  attributes :cooking_time, :video_link, :level

  has_many :comments
```

2022-07-18 11:53 UTC, grabomarcin approved these changes
LGTM

2022-07-18 11:54 UTC, merged